spring:
  application:
    name: core-service

  datasource:
    url: jdbc:postgresql://localhost:5432/BlueTrident7
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use update/create-drop/validate as per need
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

