spring:
  application:
    name: core-service

  datasource:
    url: jdbc:postgresql://localhost:5432/BlueTrident7
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev

  devtools:
    restart:
      enabled: true

jwt:
  secret: shifor07SecretKeyForHS256Algorithm1234
  expiration: 3600000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080

# CORS Configuration
app:
  cors:
    allowed-origins:
      - http://localhost:4550
      - https://cipher07.com

razorpay:
  key-id: rzp_test_RPnauMGWcIXnOm
  key-secret: liSw6QUXgdRufdCWFqqKxLJ5

